[package]
name = "http-cache-semantics"
description = "RFC 7234. Parses HTTP headers to correctly compute cacheability of responses, even in complex cases"
homepage = "https://github.com/kornelski/http-cache-semantics"
repository = "https://github.com/kornelski/rusty-http-cache-semantics"
documentation = "https://docs.rs/http-cache-semantics"
license = "BSD-2-Clause"
version = "0.5.0"
authors = ["Kornel <kornel@geekhood.net>", "Luna Graysen <luna.g@protonmail.com>", "Douglas Greenshields <dgreenshields@gmail.com>", "Kat Marchán <kzm@zkat.tech>"]
edition = "2018"
categories = ["caching", "web-programming::http-client"]
keywords = ["http", "cache", "headers", "cache-control", "proxy"]
include = ["Cargo.toml", "README.md", "src/*.rs", "LICENSE"]
readme = "README.md"

[dependencies]
chrono = "0.4.10"
http = "0.2.0"
http-serde = "1.0.0"
serde = { version = "1.0.104", optional = true }
serde_derive = { version = "1.0.104", optional = true }
reqwest = { version = "0.10.1", optional = true }

[dev-dependencies]
serde_json = "1.0.47"

[features]
default = ["with_serde"]
with_serde = ["serde", "serde_derive"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
