on:
  push:
    branches:
    - main
  pull_request:

name: CI

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "--deny warnings"
  RUSTDOCFLAGS: "--deny warnings"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Install ${{ matrix.rust }} toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal --component clippy,rustfmt
          rustup default ${{ matrix.rust }}
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Build all targets
        run: cargo build --all-targets --all-features
      - name: Run the test suite
        run: cargo test --all-features
      - name: Commune with clippy
        run: cargo clippy
      - name: Check docs
        run: cargo doc
