on:
  push:
    branches:
    - main
  pull_request:

name: CI

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "--deny warnings"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ matrix.rust }} toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal --component rustfmt
          rustup default ${{ matrix.rust }}
      - name: Check formatting
        run: |
          cargo fmt --all -- --check
      - name: Run the test suite
        run: |
          cargo test --all-features
      - name: Check docs
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc
